apiVersion: v1
kind: Service
metadata:
  name: frontend-clima-service
spec:
  type: NodePort
  selector:
    app: frontend-clima-app
  ports:
    - port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-clima-deployment
spec:
  selector:
    matchLabels:
      app: frontend-clima-app
  template:
    metadata:
      labels:
        app: frontend-clima-app
    spec:
      containers:
        - name: frontend-clima-container
          image: ghcr.io/debora-alayo/frontendgranja:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

